# IMC Prosperity 4 — Round 5 Trader (rolling TLS β pair trading)
# Generated by round5_analysis.ipynb Cell 22.
# Position limit: ±10 per product. All Order prices int()-wrapped.

import json, math
from typing import List
from datamodel import OrderDepth, TradingState, Order


# ─── PAIR CONFIG ────────────────────────────────────────────────────────
# Each tuple: (Y, X, beta_init, entry_z, exit_z, qty_per_leg)
SELECTED_PAIRS = [
    ('SLEEP_POD_LAMB_WOOL', 'SLEEP_POD_NYLON', 0.40054, 1.5, 0.3, 5),
    ('SNACKPACK_PISTACHIO', 'SNACKPACK_RASPBERRY', -1.21918, 1.5, 0.3, 5),
]


# ─── HYPERPARAMETERS ───────────────────────────────────────────────────
POS_LIMIT          = 10      # IMC hard limit per product
BETA_WIN           = 500     # rolling β window (ticks)
Z_WIN              = 300     # z-score window
BETA_REFRESH       = 50      # recompute β every K ticks
MIN_HIST_FOR_TRADE = 150     # require this many ticks before any signal
MAX_BETA_JUMP_PCT  = 2.0     # reject β updates that flip by >200%


def tls_beta_2x2(y_list, x_list):
    """Closed-form TLS β via smallest-eigvec of 2×2 demeaned covariance."""
    n = len(x_list)
    if n < 30:
        return None
    mx = sum(x_list) / n
    my = sum(y_list) / n
    sxx = syy = sxy = 0.0
    for xi, yi in zip(x_list, y_list):
        dx, dy = xi - mx, yi - my
        sxx += dx*dx
        syy += dy*dy
        sxy += dx*dy
    disc    = math.sqrt((sxx - syy)**2 + 4*sxy*sxy)
    lam_min = 0.5 * ((sxx + syy) - disc)
    denom   = lam_min - sxx
    return -sxy / denom if abs(denom) > 1e-12 else None


def _mid(state, p):
    od = state.order_depths.get(p)
    if od is None or not od.buy_orders or not od.sell_orders:
        return None
    return (max(od.buy_orders) + min(od.sell_orders)) / 2.0


def _best_bid(state, p):
    od = state.order_depths.get(p)
    return int(max(od.buy_orders)) if od and od.buy_orders else None


def _best_ask(state, p):
    od = state.order_depths.get(p)
    return int(min(od.sell_orders)) if od and od.sell_orders else None


def _max_qty(base_qty, y_pos, x_pos, beta, direction):
    """Max ΔY that keeps both legs within ±POS_LIMIT after the trade.

    Long spread:  +ΔY on Y,  −β·ΔY on X   (sign='long', x_per_y = −β)
    Short spread: −ΔY on Y,  +β·ΔY on X   (sign='short', x_per_y = +β)
    """
    if direction == "long":
        cap_y   = POS_LIMIT - y_pos
        x_per_y = -beta
    else:
        cap_y   = POS_LIMIT + y_pos
        x_per_y = beta
    if abs(x_per_y) < 1e-9:
        cap_x = base_qty
    elif x_per_y > 0:
        cap_x = (POS_LIMIT - x_pos) / x_per_y
    else:
        cap_x = (POS_LIMIT + x_pos) / abs(x_per_y)
    return max(0, min(base_qty, int(cap_y), int(cap_x)))


class Trader:
    def run(self, state: TradingState):
        result = {}
        td = json.loads(state.traderData) if state.traderData else {}

        for (Y, X, beta_init, entry_z, exit_z, base_qty) in SELECTED_PAIRS:
            y_mid = _mid(state, Y)
            x_mid = _mid(state, X)
            if y_mid is None or x_mid is None:
                continue

            key = Y + "|" + X
            ps = td.get(key, {
                "y_hist": [], "x_hist": [], "sp_hist": [],
                "beta":   float(beta_init), "tick": 0,
            })

            # ── Update price history (capped at BETA_WIN) ──
            ps["y_hist"].append(y_mid)
            ps["x_hist"].append(x_mid)
            if len(ps["y_hist"]) > BETA_WIN:
                ps["y_hist"] = ps["y_hist"][-BETA_WIN:]
                ps["x_hist"] = ps["x_hist"][-BETA_WIN:]
            ps["tick"] += 1

            # ── Refresh β every K ticks (with sanity check) ──
            if ps["tick"] % BETA_REFRESH == 0 and len(ps["y_hist"]) >= 100:
                new_b = tls_beta_2x2(ps["y_hist"], ps["x_hist"])
                if new_b is not None:
                    rel_jump = abs(new_b - ps["beta"]) / max(abs(ps["beta"]), 1e-9)
                    if rel_jump < MAX_BETA_JUMP_PCT:
                        ps["beta"] = new_b

            beta = ps["beta"]

            # ── Spread + z-score ──
            sp_now = y_mid - beta * x_mid
            ps["sp_hist"].append(sp_now)
            if len(ps["sp_hist"]) > Z_WIN:
                ps["sp_hist"] = ps["sp_hist"][-Z_WIN:]

            td[key] = ps
            if len(ps["sp_hist"]) < MIN_HIST_FOR_TRADE:
                continue

            mu  = sum(ps["sp_hist"]) / len(ps["sp_hist"])
            var = sum((s - mu)**2 for s in ps["sp_hist"]) / len(ps["sp_hist"])
            sig = math.sqrt(var) if var > 1e-12 else 1e-9
            z   = (sp_now - mu) / sig

            y_pos = state.position.get(Y, 0)
            x_pos = state.position.get(X, 0)

            y_ords, x_ords = [], []

            # ── ENTRY: SHORT spread (z > +entry_z) ──
            #   spread above mean → sell Y, buy β·X (sign of β determines X side)
            if z > entry_z and y_pos > -POS_LIMIT:
                qty_y = _max_qty(base_qty, y_pos, x_pos, beta, "short")
                if qty_y > 0:
                    hedge_x = int(round(beta * qty_y))
                    y_bid = _best_bid(state, Y)
                    if y_bid is not None:
                        y_ords.append(Order(Y, int(y_bid), -qty_y))
                    if hedge_x > 0:
                        x_ask = _best_ask(state, X)
                        if x_ask is not None:
                            x_ords.append(Order(X, int(x_ask), hedge_x))
                    elif hedge_x < 0:
                        x_bid = _best_bid(state, X)
                        if x_bid is not None:
                            x_ords.append(Order(X, int(x_bid), hedge_x))

            # ── ENTRY: LONG spread (z < -entry_z) ──
            elif z < -entry_z and y_pos < POS_LIMIT:
                qty_y = _max_qty(base_qty, y_pos, x_pos, beta, "long")
                if qty_y > 0:
                    hedge_x = int(round(beta * qty_y))
                    y_ask = _best_ask(state, Y)
                    if y_ask is not None:
                        y_ords.append(Order(Y, int(y_ask), qty_y))
                    if hedge_x > 0:
                        x_bid = _best_bid(state, X)
                        if x_bid is not None:
                            x_ords.append(Order(X, int(x_bid), -hedge_x))
                    elif hedge_x < 0:
                        x_ask = _best_ask(state, X)
                        if x_ask is not None:
                            x_ords.append(Order(X, int(x_ask), -hedge_x))

            # ── EXIT: |z| crossed back near zero → flatten both legs ──
            elif abs(z) < exit_z:
                if y_pos > 0:
                    p = _best_bid(state, Y)
                    if p is not None: y_ords.append(Order(Y, int(p), -y_pos))
                elif y_pos < 0:
                    p = _best_ask(state, Y)
                    if p is not None: y_ords.append(Order(Y, int(p), -y_pos))
                if x_pos > 0:
                    p = _best_bid(state, X)
                    if p is not None: x_ords.append(Order(X, int(p), -x_pos))
                elif x_pos < 0:
                    p = _best_ask(state, X)
                    if p is not None: x_ords.append(Order(X, int(p), -x_pos))

            if y_ords: result.setdefault(Y, []).extend(y_ords)
            if x_ords: result.setdefault(X, []).extend(x_ords)

        return result, 0, json.dumps(td)
